export const ADD_TASK = 'ADD_TASK'
export const GET_TASKS = 'GET_TASKS'
export const UPDATE_TASK = 'UPDATE_TASK'
export const CLEAR_TRASH = 'CLEAR_TRASH'

export const ADD_PROJECT = 'ADD_PROJECT'
export const GET_PROJECTS = 'GET_PROJECTS'

export const ADD_TAG = 'ADD_TAG'
export const GET_TAGS = 'GET_TAGS'

export const SET_PRIORITY = 'SET_PRIORITY'
export const SET_TASK_NAME = 'SET_TASK_NAME'
export const SET_TASK_DATE = 'SET_TASK_DATE'

export const TOGGLE_SIDEDEBAR_VISIBILITY = 'TOGGLE_SIDEDEBAR_VISIBILITY'
export const SET_DONE_MESSAGE_VISIBILITY = 'SET_DONE_MESSAGE_VISIBILITY'
export const SET_DELETED_MESSAGE_VISIBILITY = 'SET_DELETED_MESSAGE_VISIBILITY'
export const SET_DONE_ID_TASK = 'SET_DONE_ID_TASK'
export const SET_DELETED_ID_TASK = 'SET_DELETED_ID_TASK'
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB'
export const SET_CURRENT_PROJECT_ID = 'SET_CURRENT_PROJECT_ID'
export const SET_CURRENT_TAG_ID = 'SET_CURRENT_TAG_ID'

export const SET_CREATE_PROJECT = 'SET_CREATE_PROJECT'
export const SET_CREATE_TAG = 'SET_CREATE_TAG'