export const ADD_TASK = 'ADD_TASK'
export const GET_TASKS = 'GET_TASKS'

export const SET_PRIORITY = 'SET_PRIORITY'
export const SET_TASK_NAME = 'SET_TASK_NAME'

export const TOGGLE_SIDEDEBAR_VISIBILITY = 'TOGGLE_SIDEDEBAR_VISIBILITY'